In [2]:
import pandas as pd

In [3]:
df = pd.read_parquet('./data/stats_player_reg_2025.parquet')
df.columns.to_list()
# df['position_group'].unique()

df["fantasy_points_hppr"] = (df["fantasy_points"] + df["fantasy_points_ppr"]) / 2
df["hppr_points_per_game"] = df["fantasy_points_hppr"] / df["games"]

position_dfs = []

for pos in ["QB", "RB", "WR", "TE"]:
    pos_df = df[df["position"] == pos]

    pos_df["turnovers"] = pos_df["rushing_fumbles_lost"] + pos_df["receiving_fumbles_lost"] + pos_df["sack_fumbles_lost"] + pos_df["passing_interceptions"]
    pos_df["rank_ppg"] = pos_df["hppr_points_per_game"].rank(ascending=False, method="min")
    pos_df["rank_total"] = pos_df["fantasy_points_hppr"].rank(ascending=False, method="min")
    pos_df["position_tier"] = (pos_df["rank_ppg"] - 1) // 12 + 1

    position_dfs.append(pos_df)

unified_positional_df = pd.concat(position_dfs, ignore_index=True)
sorted_unified = unified_positional_df.sort_values(by="season", ascending=False)
sorted_unified.head(25)

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,season_type,recent_team,games,...,gwfg_blocked,gwfg_distance_list,fantasy_points,fantasy_points_ppr,fantasy_points_hppr,hppr_points_per_game,turnovers,rank_ppg,rank_total,position_tier
0,00-0022942,P.Rivers,Philip Rivers,QB,QB,https://static.www.nfl.com/image/private/f_aut...,2025,REG,IND,3,...,0,NaN,31.66,31.66,31.66,10.553333,3,42.0,49.0,4.0
409,00-0039650,B.Oliver,Bryce Oliver,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,TEN,2,...,0,NaN,0.80,1.80,1.30,0.650000,0,204.0,217.0,17.0
402,00-0039410,R.Flournoy,Ryan Flournoy,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,DAL,15,...,0,NaN,74.00,114.00,94.00,6.266667,0,66.0,55.0,6.0
403,00-0039424,D.Vele,Devaughn Vele,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,NO,9,...,0,NaN,41.30,66.30,53.80,5.977778,0,69.0,95.0,6.0
404,00-0039451,I.Williams,Isaiah Williams,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,NYJ,15,...,0,NaN,34.70,60.70,47.70,3.180000,0,131.0,100.0,11.0
405,00-0039491,J.Coker,Jalen Coker,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,CAR,11,...,0,NaN,57.40,90.40,73.90,6.718182,1,62.0,68.0,6.0
406,00-0039521,X.Weaver,Xavier Weaver,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,ARI,7,...,0,NaN,6.70,13.70,10.20,1.457143,0,178.0,173.0,15.0
407,00-0039589,K.Johnson,Kameron Johnson,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,TB,17,...,0,NaN,13.70,17.70,15.70,0.923529,0,192.0,154.0,16.0
408,00-0039623,M.Tipton,Mason Tipton,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,NO,8,...,0,NaN,9.40,20.40,14.90,1.862500,0,164.0,157.0,14.0
410,00-0039710,J.Jones,Jeshaun Jones,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,MIN,1,...,0,NaN,0.00,0.00,0.00,0.000000,0,220.0,220.0,19.0
457,00-0040563,E.Chism,Efton Chism III,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,NE,8,...,0,NaN,13.50,16.50,15.00,1.875000,0,163.0,156.0,14.0
411,00-0039739,R.Wilson,Roman Wilson,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,PIT,9,...,0,NaN,26.60,38.60,32.60,3.622222,1,112.0,122.0,10.0
412,00-0039751,J.Whittington,Jordan Whittington,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,LA,15,...,0,NaN,18.30,36.30,27.30,1.820000,0,165.0,131.0,14.0
413,00-0039792,D.Walker,Devontez Walker,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,BAL,8,...,0,NaN,31.60,37.60,34.60,4.325000,0,100.0,120.0,9.0
414,00-0039816,A.Gould,Anthony Gould,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,IND,11,...,0,NaN,0.60,2.60,1.60,0.145455,0,218.0,214.0,19.0
415,00-0039849,M.Harrison,Marvin Harrison Jr.,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,ARI,12,...,0,NaN,86.80,127.80,107.30,8.941667,0,39.0,49.0,4.0
416,00-0039855,J.McMillan,Jalen McMillan,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,TB,4,...,0,NaN,17.90,29.90,23.90,5.975000,0,70.0,139.0,6.0
417,00-0039868,T.Franklin,Troy Franklin,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,DEN,17,...,0,NaN,112.10,177.10,144.60,8.505882,1,44.0,33.0,4.0
401,00-0039394,Cas.Washington,Casey Washington,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,ATL,5,...,0,NaN,9.40,15.40,12.40,2.480000,0,149.0,165.0,13.0
400,00-0039379,J.Thrash,Jamari Thrash,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,CLE,8,...,0,NaN,10.70,20.70,15.70,1.962500,0,160.0,153.0,14.0
399,00-0039355,L.McCaffrey,Luke McCaffrey,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,WAS,9,...,0,NaN,40.30,51.30,45.80,5.088889,0,81.0,103.0,7.0
398,00-0039342,X.Legette,Xavier Legette,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,CAR,15,...,0,NaN,54.30,89.30,71.80,4.786667,0,90.0,71.0,8.0
383,00-0038840,B.Tremayne,Brycen Tremayne,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,CAR,15,...,0,NaN,16.00,30.00,23.00,1.533333,0,175.0,142.0,15.0
384,00-0038891,S.Jackson,Shedrick Jackson,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,LV,3,...,0,NaN,11.90,15.90,13.90,4.633333,0,96.0,160.0,8.0
385,00-0038911,M.Cunningham,Malik Cunningham,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2025,REG,DET,1,...,0,NaN,0.10,0.10,0.10,0.100000,0,219.0,219.0,19.0

In [4]:
df["fantasy_points_hppr"] = (df["fantasy_points"] + df["fantasy_points_ppr"]) / 2
df["hppr_points_per_game"] = df["fantasy_points_hppr"] / df["games"]

In [5]:
# wr data

# wr_df = df.query("position == 'WR' & games > 8")
wr_df = df.query("position == 'WR'")

wr_df["rank_ppg"] = wr_df['hppr_points_per_game'].rank(ascending=False, method='min')
wr_df["rank_total"] = wr_df['fantasy_points_hppr'].rank(ascending=False, method='min')
sorted_wr_df = wr_df.sort_values(by="rank_ppg")

wr1s = sorted_wr_df[["rank_ppg", "rank_total", "player_display_name", "games", "fantasy_points_hppr", "hppr_points_per_game"]]
wr1s.head(24)

,rank_ppg,rank_total,player_display_name,games,fantasy_points_hppr,hppr_points_per_game
1413,1.0,1.0,Puka Nacua,16,310.5,19.406250
1222,2.0,2.0,Jaxon Smith-Njigba,17,300.4,17.670588
842,3.0,4.0,Ja'Marr Chase,16,251.1,15.693750
877,4.0,3.0,Amon-Ra St. Brown,17,265.5,15.617647
1407,5.0,41.0,Rashee Rice,8,123.6,15.450000
974,6.0,5.0,George Pickens,17,245.4,14.435294
966,7.0,17.0,Drake London,12,167.9,13.991667
73,8.0,8.0,Davante Adams,14,192.9,13.778571
967,9.0,6.0,Chris Olave,16,218.0,13.625000
754,10.0,9.0,Nico Collins,15,190.7,12.713333
696,11.0,20.0,CeeDee Lamb,13,163.4,12.569231
720,12.0,12.0,Tee Higgins,15,182.1,12.140000
552,13.0,14.0,A.J. Brown,15,181.3,12.086667
1471,14.0,99.0,Malik Nabers,4,48.1,12.025000
1404,15.0,7.0,Zay Flowers,17,200.3,11.782353
1089,16.0,62.0,Garrett Wilson,7,81.5,11.642857
1161,17.0,42.0,Christian Watson,10,114.9,11.490000
1223,18.0,32.0,Quentin Johnston,13,145.7,11.207692
968,19.0,10.0,Jameson Williams,17,187.4,11.023529
156,20.0,109.0,Tyreek Hill,4,43.0,10.750000
321,21.0,11.0,Courtland Sutton,17,182.7,10.747059
1155,22.0,16.0,Wan'Dale Robinson,16,171.9,10.743750
1237,23.0,13.0,Michael Wilson,17,181.6,10.682353
1083,24.0,24.0,Alec Pierce,15,159.8,10.653333

In [6]:
# rb data

# rb_df = df.query("position == 'RB' & games > 8")
rb_df = df.query("position == 'RB'")
rb_df["rank_ppg"] = rb_df['hppr_points_per_game'].rank(ascending=False, method='min')
rb_df["rank_total"] = rb_df['fantasy_points_hppr'].rank(ascending=False, method='min')
sorted_rb_df = rb_df.sort_values(by="rank_ppg")

rbs = sorted_rb_df[["rank_ppg", "rank_total", "player_display_name", "games", "fantasy_points_hppr", "hppr_points_per_game"]]
rbs.head(24)

,rank_ppg,rank_total,player_display_name,games,fantasy_points_hppr,hppr_points_per_game
182,1.0,1.0,Christian McCaffrey,17,365.60,21.505882
634,2.0,2.0,Jonathan Taylor,17,339.30,19.958824
1221,3.0,3.0,Bijan Robinson,17,331.30,19.488235
1422,4.0,4.0,Jahmyr Gibbs,17,328.40,19.317647
1391,5.0,5.0,De'Von Achane,16,289.30,18.081250
975,6.0,6.0,James Cook,17,285.70,16.805882
144,7.0,7.0,Derrick Henry,17,272.00,16.000000
566,8.0,12.0,Josh Jacobs,15,219.10,14.606667
1265,9.0,8.0,Chase Brown,17,248.10,14.594118
1981,10.0,39.0,Cam Skattebo,8,115.70,14.462500
1130,11.0,9.0,Kyren Williams,17,245.30,14.429412
903,12.0,11.0,Javonte Williams,16,225.30,14.081250
884,13.0,10.0,Travis Etienne,17,235.90,13.876471
409,14.0,14.0,Saquon Barkley,16,213.80,13.362500
1958,15.0,36.0,Omarion Hampton,9,119.70,13.300000
653,16.0,15.0,D'Andre Swift,16,211.60,13.225000
1750,17.0,13.0,Ashton Jeanty,17,217.60,12.800000
1492,18.0,33.0,Bucky Irving,10,123.50,12.350000
960,19.0,16.0,Jaylen Warren,16,197.10,12.318750
1158,20.0,18.0,Breece Hall,16,189.66,11.853750
829,21.0,25.0,Rhamondre Stevenson,14,162.80,11.628571
610,22.0,17.0,Rico Dowdle,17,196.80,11.576471
2018,23.0,26.0,Quinshon Judkins,14,156.80,11.200000
1998,24.0,19.0,TreVeyon Henderson,17,188.70,11.100000

In [7]:
# qb data

# qb_df = df.query("position == 'QB' & games > 8")
qb_df = df.query("position == 'QB'")
qb_df["rank_ppg"] = qb_df['hppr_points_per_game'].rank(ascending=False, method='min')
qb_df["rank_total"] = qb_df['fantasy_points_hppr'].rank(ascending=False, method='min')
sorted_qb_df = qb_df.sort_values(by="rank_ppg")

qbs = sorted_qb_df[["rank_ppg", "rank_total", "player_display_name", "games", "fantasy_points_hppr", "hppr_points_per_game"]]
qbs.head(24)

,rank_ppg,rank_total,player_display_name,games,fantasy_points_hppr,hppr_points_per_game
414,1.0,1.0,Josh Allen,16,364.62,22.788750
1654,2.0,2.0,Drake Maye,17,351.46,20.674118
8,3.0,3.0,Matthew Stafford,17,350.38,20.610588
244,4.0,11.0,Patrick Mahomes,14,285.18,20.370000
882,5.0,4.0,Trevor Lawrence,17,338.18,19.892941
1125,6.0,23.0,Brock Purdy,9,177.38,19.708889
711,7.0,8.0,Jalen Hurts,16,301.06,18.816250
1700,8.0,5.0,Caleb Williams,17,317.18,18.657647
167,9.0,6.0,Dak Prescott,17,313.78,18.457647
1588,10.0,7.0,Bo Nix,17,304.84,17.931765
694,11.0,10.0,Justin Herbert,16,286.88,17.930000
170,12.0,9.0,Jared Goff,17,297.06,17.474118
571,13.0,18.0,Daniel Jones,13,226.44,17.418462
1971,14.0,13.0,Jaxson Dart,14,241.58,17.255714
737,15.0,29.0,Joe Burrow,8,134.46,16.807500
390,16.0,20.0,Lamar Jackson,13,214.86,16.527692
1693,17.0,34.0,Jayden Daniels,7,114.28,16.325714
173,18.0,16.0,Jacoby Brissett,14,227.44,16.245714
412,19.0,12.0,Baker Mayfield,17,271.92,15.995294
867,20.0,28.0,Justin Fields,9,142.66,15.851111
649,21.0,15.0,Jordan Love,15,235.14,15.676000
464,22.0,38.0,Kyler Murray,5,77.78,15.556000
1438,23.0,21.0,C.J. Stroud,14,208.54,14.895714
2007,24.0,26.0,Tyler Shough,11,157.96,14.360000

In [8]:
# te data

# te_df = df.query("position == 'TE' & games > 10")
te_df = df.query("position == 'TE'")
te_df["rank_ppg"] = te_df['hppr_points_per_game'].rank(ascending=False, method='min')
te_df["rank_total"] = te_df['fantasy_points_hppr'].rank(ascending=False, method='min')
sorted_te_df = te_df.sort_values(by="rank_ppg")

qbs = sorted_te_df[["rank_ppg", "rank_total", "player_display_name", "games", "fantasy_points_hppr", "hppr_points_per_game"]]
qbs.head(24)

,rank_ppg,rank_total,player_display_name,games,fantasy_points_hppr,hppr_points_per_game
1093,1.0,1.0,Trey McBride,17,252.9,14.876471
1374,2.0,21.0,Tucker Kraft,8,101.2,12.650000
186,3.0,13.0,George Kittle,11,133.0,12.090909
1472,4.0,9.0,Brock Bowers,12,144.2,12.016667
323,5.0,4.0,Dallas Goedert,15,155.1,10.340000
881,6.0,2.0,Kyle Pitts,17,166.8,9.811765
1405,7.0,27.0,Sam LaPorta,9,86.9,9.655556
1957,8.0,6.0,Harold Fannin Jr.,16,150.4,9.400000
49,9.0,3.0,Travis Kelce,17,155.2,9.129412
1353,10.0,18.0,Dalton Kincaid,12,106.6,8.883333
1756,11.0,5.0,Tyler Warren,17,150.5,8.852941
168,12.0,7.0,Hunter Henry,17,148.8,8.752941
1137,13.0,8.0,Jake Ferguson,17,147.1,8.652941
89,14.0,30.0,Darren Waller,9,76.7,8.522222
1754,15.0,12.0,Colston Loveland,16,136.1,8.506250
600,16.0,10.0,Juwan Johnson,17,141.4,8.317647
337,17.0,11.0,Dalton Schultz,17,136.7,8.041176
1355,18.0,23.0,Brenton Strange,12,95.0,7.916667
41,19.0,20.0,Zach Ertz,13,101.4,7.800000
639,20.0,15.0,Colby Parkinson,14,108.3,7.735714
937,21.0,31.0,Jake Tonges,10,76.3,7.630000
1621,22.0,14.0,AJ Barner,17,121.3,7.135294
1810,23.0,17.0,Oronde Gadsden II,15,106.9,7.126667
1651,24.0,19.0,Theo Johnson,15,105.3,7.020000